mysql -h php-system-bj.c3vdzrglae3k.ap-southeast-1.rds.amazonaws.com -udb_app -pVee8lie3aiNee9sa -N -e "delete from new_ssp.cap_daily_cost"
#mysql -h 10.17.15.98 -udb_app -pVee8lie3aiNee9sa -N -e "select * from new_ssp.cap_daily_cost"
mysql -h php-system-bj.c3vdzrglae3k.ap-southeast-1.rds.amazonaws.com -udb_app -pVee8lie3aiNee9sa -N -e "delete from new_ssp.fenix_click_cvr "
mysql -h php-system-bj.c3vdzrglae3k.ap-southeast-1.rds.amazonaws.com -udb_app -pVee8lie3aiNee9sa -N -e "delete from new_ssp.target_pacing "
mysql -h php-system-bj.c3vdzrglae3k.ap-southeast-1.rds.amazonaws.com -udb_app -pVee8lie3aiNee9sa -N -e "delete from new_ssp.realtime_cvr "
