export PGPASSWORD=Cloudtech2018
echo "$(date) begin" > log
day=$(date -d "3 days ago" "+%Y%m%d")
begin_day=$(date -d "3 days ago" "+%Y%m%d00")
end_day=$(date -d "1 days ago" "+%Y%m%d23")

echo $begin_day
echo $end_day
echo "select * from (SELECT coalesce(ta.day,tb.day), coalesce(ta.hour,tb.hour), coalesce(ta.platform,tb.platform), coalesce(ta.country,tb.country), coalesce(ta.channel,tb.channel), coalesce(ta.click,0) as click, coalesce(tb.conv,0) as conv, coalesce(tb.payout,0) as payout FROM ( SELECT SUBSTRING ( time_slot, 1, 8 ) AS DAY, SUBSTRING( time_slot, 9, 10) AS hour, platform, country, channel, SUM ( COUNT ) click  FROM impression  WHERE time_slot >='$begin_day'  AND time_slot <='$end_day' AND country != 'CN'  GROUP BY DAY, hour, platform, country, channel  ) ta right JOIN ( SELECT SUBSTRING ( time_slot, 1, 8 ) AS DAY, SUBSTRING( time_slot, 9, 10) AS hour, platform, country, channel, SUM ( COUNT ) conv, SUM ( payout ) payout  FROM CONVERSION  WHERE time_slot >='$begin_day'  AND time_slot <='$end_day'  AND country != 'CN'  GROUP BY DAY, hour, platform, country, channel  ) tb ON (  ta.platform = tb.platform  AND ta.country = tb.country  AND ta.channel = tb.channel  AND ta.DAY = tb.DAY and ta.hour = tb.hour) union SELECT coalesce(ta.day,tb.day), coalesce(ta.hour,tb.hour), coalesce(ta.platform,tb.platform), coalesce(ta.country,tb.country), coalesce(ta.channel,tb.channel), coalesce(ta.click,0) as click, coalesce(tb.conv,0) as conv, coalesce(tb.payout,0) as payout FROM ( SELECT SUBSTRING ( time_slot, 1, 8 ) AS DAY, SUBSTRING( time_slot, 9, 10) AS hour, platform, country, channel, SUM ( COUNT ) click  FROM impression  WHERE time_slot >='$begin_day'  AND time_slot <='$end_day'  AND country != 'CN'  GROUP BY DAY, hour, platform, country, channel  ) ta left JOIN ( SELECT SUBSTRING ( time_slot, 1, 8 ) AS DAY, SUBSTRING( time_slot, 9, 10) AS hour, platform, country, channel, SUM ( COUNT ) conv, SUM ( payout ) payout  FROM CONVERSION  WHERE time_slot >='$begin_day'  AND time_slot <='$end_day'  AND country != 'CN'  GROUP BY DAY, hour, platform, country, channel  ) tb ON (  ta.platform = tb.platform  AND ta.country = tb.country  AND ta.channel = tb.channel  AND ta.DAY = tb.DAY and ta.hour = tb.hour ) )aa"| psql -h cloudmobi-realtime.c3otanzuchnc.ap-southeast-1.redshift.amazonaws.com -p 5439 --user cloudtech --db monitor -F "	" -t -A > day_report_ssp.data

echo "delete from  ssp_system.day_report_ssp where day=$day;load data local infile '/opt/ReportApi/scripts/ssp/day_report_ssp.data' into table ssp_system.day_report_ssp;" | mysql -hssp-system-bj.c3vdzrglae3k.ap-southeast-1.rds.amazonaws.com -umysql -pyeahmobi

